download latest git-TEST-commit-automation/hooks

diff --git a/hooks/EXAMPLES/SA-exit-code-error-124-002 b/hooks/EXAMPLES/SA-exit-code-error-124-002
--- a/hooks/EXAMPLES/SA-exit-code-error-124-002
+++ b/hooks/EXAMPLES/SA-exit-code-error-124-002
@@ -1,9 +1,7 @@
 #!/bin/bash
-#	hooks/EXAMPLES/SAST-exit-code-error-2-001  3.488.743  2019-08-31T23:13:39.252948-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.487  
-#	   SCRIPT_VERSION incident corrected and correct Test script logic ERROR message 
-#	hooks/EXAMPLES/SAST-exit-code-error-2-001  3.488.743  2019-08-31T23:11:27.607782-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.487  
-#	   SCRIPT_VERSION incident corrected and correct Test script logic ERROR message 
-###  hooks/EXAMPLES/SAST-exit-code-error-2-001 - test case
+#	hooks/EXAMPLES/SA-exit-code-error-124-002  2.4.279  2019-09-01T15:00:05.270453-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.3-5-gaab1b24  
+#	   hooks/bin/list-git-TEST-cases.sh Rename SAST to SA for Static Analysis close #1 
+###  hooks/EXAMPLES/SA-exit-code-error-124-002 - test case
 ###  Production standard 3.0 shellcheck
 ###  Production standard 5.1.160 Copyright
 #    Copyright (c) 2019 Bradley Allen
@@ -45,6 +43,6 @@ if [[ "${DEBUG}" == "1" ]] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAM
 
 ###     Place test case here
 
-echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 2 - exit code 2: report test case error exit code total - ${BOLD}ERROR - ERROR${NORMAL}"
-exit 2
+echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 124 - exit code 124: report test case error exit code total - ${BOLD}ERROR - ERROR${NORMAL}"
+exit 124
 ###
diff --git a/hooks/EXAMPLES/SA-exit-code-error-2-001 b/hooks/EXAMPLES/SA-exit-code-error-2-001
--- a/hooks/EXAMPLES/SA-exit-code-error-2-001
+++ b/hooks/EXAMPLES/SA-exit-code-error-2-001
@@ -1,7 +1,7 @@
 #!/bin/bash
-#	hooks/EXAMPLES/SAST-exit-code-error-124-001  3.487.742  2019-08-31T21:38:21.432019-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.486  
-#	   hooks/EXAMPLES/SAST-exit-code-error-124-001   change tab to two spaces update Production standard 1.3.475 DEBUG variable 
-###  hooks/EXAMPLES/SAST-exit-code-error-124-001 - test case
+#	hooks/EXAMPLES/SA-exit-code-error-2-001  2.4.279  2019-09-01T15:00:09.338864-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.3-5-gaab1b24  
+#	   hooks/bin/list-git-TEST-cases.sh Rename SAST to SA for Static Analysis close #1 
+###  hooks/EXAMPLES/SA-exit-code-error-2-001 - test case
 ###  Production standard 3.0 shellcheck
 ###  Production standard 5.1.160 Copyright
 #    Copyright (c) 2019 Bradley Allen
@@ -43,6 +43,6 @@ if [[ "${DEBUG}" == "1" ]] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAM
 
 ###     Place test case here
 
-echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}ERROR - ERROR${NORMAL}"
-exit 124
+echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 2 - exit code 2: report test case error exit code total - ${BOLD}ERROR - ERROR${NORMAL}"
+exit 2
 ###
